AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless api

#Globals:
#  Function:
#    Environment:
#      Variables:
#        DB_URI:

Resources:
  ServerlessService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: src/
      Description: Serverless function to handle get requests
      MemorySize: 128
      Timeout: 10
      Events:
        apiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /
